import Head from "next/head";
import Image from "next/image";
import data from "./api/data.json";

export default function Home({ itemData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="m-4 text-3xl text-center font-bold">Welcome to <a href="https://nextjs.org" className="text-blue-600	hover:underline">Next.js</a>!</h1>

        <div className="flex justify-evenly flex-wrap">
          {itemData.map((item) => {
            return (
              <div key={item.img} className="m-5 w-[350px]">
                <p className="font-bold text-lg">{item.name}</p>
                <Image src={`/images/${item.img}`} width={350} height={350} />
                <p>{item.desc}</p>
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  return {
    props: { itemData: data.items },
  };
};
